# Deploys changed flows to the appropriate Prefect Cloud workspace
name: Deploy flows to Workspace

on:
  workflow_call:
    inputs:
      prefect-workspace:
        description: "Prefect workspace to deploy to"
        required: true
        type: string
    secrets:
      prefect-api-key:
        description: "Prefect API Key for Prefect Cloud"
        required: true
      prefect-api-url:
        description: "Prefect API URL to Prefect Cloud"
        required: true
      

env:
  PREFECT_API_KEY: ${{ secrets.prefect-api-key }}
  PREFECT_API_URL: ${{ secrets.prefect-api-url }}

jobs:
  deploy_flows:
    name: "Deploy Flows"
    runs-on: ubuntu-latest
    
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
  
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install Prefect
        run: |
          pip install prefect

      - name: Get list of modified python files
        id: getfile
        run: |
          files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^.*\.py$' | tr '\n' ',')
          echo "Modified Python files: $files"
          echo "files=$files" >> $GITHUB_ENV

      - name: Set Prefect Workspace
        run: prefect cloud workspace set -w ${{ inputs.prefect-workspace }}

      - name: Deploy flows in branch defined in modified files
        run: |
          entrypoints=$(python scripts/get_flow_entrypoints.py)
          echo "Found entrypoints: $entrypoints"
          IFS="," read -ra ENTRYPOINTS <<< "$entrypoints"
          IFS="," read -ra FILES <<< $files
          for entrypoint in "${ENTRYPOINTS[@]}"; do
              file=$(echo $entrypoint | cut -d ":" -f 1)
              if [[ " ${FILES[@]} " =~ " ${file} " ]]; then
                  echo "Deploying flow: $entrypoint"
                  prefect --no-prompt deploy $entrypoint
              else
                  echo "Skipping flow: $entrypoint"
              fi
          done