name: Prefect Deploy to Amazon ECS

on:
  workflow_call:

env:
  PREFECT_WORKSPACE: mutual-of-enumclaw/dw-workspace
  AWS_REGION: us-west-2 # This is our AWS region
  ECR_REPO_NAME: 674071931206.dkr.ecr.us-west-2.amazonaws.com/${{ github.event.repository.name }} # Save the ECR Repo path/URL to be used in the prefect.yaml
  GIT_REPO_NAME: ${{ github.event.repository.name }}
  GIT_REPO_URL: ${{ github.server_url }}/${{ github.repository}}.git # Save the Git Repo URL to be used in the prefect.yaml file
  GIT_REPO_BRANCH: ${{ github.ref_name }} # Save the Git Repo Branch to be used in the prefect.yaml file
  OS_ENV: ${{ github.ref_name }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ github.token }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@0e613a0980cbf65ed5b322eb7a1e075d28913a83
        with:
          aws-access-key-id: ${{ secrets.GENDEV_DEPLOY_USER_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.GENDEV_DEPLOY_USER_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@62f4f872db3836360b72999f4b87f1ff13310f3a

      - uses: int128/create-ecr-repository-action@v1
        with:
          repository: ${{ env.GIT_REPO_NAME }}
          public: false

      - name: Install Python Requirements
        run: |
          python -m pip install --upgrade pip
          git config --global user.name "Bryan-Meier"
          git config  --global user.email "bmeier@mutualofenumclaw.com"
          pip install -r requirements.txt

      - name: Set Prefect Workspace
        env:
          PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
          PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}
        run: prefect cloud workspace set --workspace "${{ env.PREFECT_WORKSPACE }}"

      - name: Prefect Deploy
        env:
          PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
          PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}
        run: prefect deploy -n ${{ env.GIT_REPO_BRANCH }}-*